# -*- coding: utf-8 -*-
"""factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XvoqRI65ospgS4Tjk3CQ_A6f1Fflwa-o
"""



"""factorial

"""

n=5
fact=1
for i in range(1,n+1):
  fact=fact*i
print(fact)